/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Component;

import Hiberneat.User.User;
import Login.Const;
import java.sql.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author admin
 */
public class Form_UpdateUser extends javax.swing.JFrame {

    public Form_UpdateUser() {

        initComponents();
        AddDate();

    }

    public void LoadDataUser() {

        txthovaten.setText(Const.user_update.getHovaTen());
        txtemail.setText("" + Const.user_update.getEmail());
        txttendangnhap.setText(Const.user_update.getUserName());
        txtdiachi.setText(Const.user_update.getDiaChi());
        if (Const.user_update.getGioitinh().equals("Nam")) {
            RdnNam.setSelected(true);
        }
        if (Const.user_update.getGioitinh().equals("Nữ")) {
            RdnNu.setSelected(true);
        }
        String NgaySinh = Const.user_update.getNgaySinh().toString();
        String[] Tachchuoi = NgaySinh.split("-");
        CbnNam.setSelectedItem(Tachchuoi[0]);
        cbnThang.setSelectedItem(Tachchuoi[1]);
        cbnNgay.setSelectedItem(Tachchuoi[2]);
        String a = "Bình Thường";
        String b = "Khóa";
        if (Const.user_update.getTrangThai().equals(a)) {
            RdnBinhThuong.setSelected(true);
            RdnKhoa.setSelected(false);
        } else if (Const.user_update.getTrangThai().equals(b)) {
            RdnKhoa.setSelected(true);
            RdnBinhThuong.setSelected(false);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        txthovaten = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        txttendangnhap = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtdiachi = new javax.swing.JTextArea();
        RdnBinhThuong = new javax.swing.JRadioButton();
        RdnKhoa = new javax.swing.JRadioButton();
        CbnNam = new javax.swing.JComboBox<>();
        cbnNgay = new javax.swing.JComboBox<>();
        cbnThang = new javax.swing.JComboBox<>();
        RdnNu = new javax.swing.JRadioButton();
        RdnNam = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        btndongy = new javax.swing.JButton();
        btnkhoiphucmatkhau = new javax.swing.JButton();
        btnhuybo = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setUndecorated(true);
        setResizable(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông Tin"));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.setLayout(null);

        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.Y_AXIS));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Họ Và Tên");
        jPanel6.add(jLabel4);

        jPanel5.add(jPanel6);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Email");
        jPanel9.add(jLabel13);

        jPanel5.add(jPanel9);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Tên Đăng Nhập");
        jPanel8.add(jLabel9);

        jPanel5.add(jPanel8);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Ngày Sinh");
        jPanel4.add(jLabel3);

        jPanel5.add(jPanel4);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Giới Tính");
        jPanel12.add(jLabel11);

        jPanel5.add(jPanel12);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Địa Chỉ");
        jPanel11.add(jLabel12);

        jPanel5.add(jPanel11);

        jPanel2.add(jPanel5);
        jPanel5.setBounds(10, 30, 230, 300);

        jPanel13.setLayout(new javax.swing.BoxLayout(jPanel13, javax.swing.BoxLayout.Y_AXIS));

        jPanel21.setAlignmentX(15.0F);
        jPanel21.setLayout(null);

        txthovaten.setAlignmentY(0.0F);
        jPanel21.add(txthovaten);
        txthovaten.setBounds(10, 10, 410, 30);

        txtemail.setAlignmentY(0.0F);
        jPanel21.add(txtemail);
        txtemail.setBounds(10, 60, 410, 30);

        txttendangnhap.setAlignmentY(0.0F);
        txttendangnhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttendangnhapActionPerformed(evt);
            }
        });
        jPanel21.add(txttendangnhap);
        txttendangnhap.setBounds(10, 110, 410, 30);

        txtdiachi.setColumns(20);
        txtdiachi.setRows(5);
        jScrollPane1.setViewportView(txtdiachi);

        jPanel21.add(jScrollPane1);
        jScrollPane1.setBounds(10, 260, 410, 100);

        RdnBinhThuong.setText("Bình Thường\n\n");
        RdnBinhThuong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RdnBinhThuongMouseClicked(evt);
            }
        });
        jPanel21.add(RdnBinhThuong);
        RdnBinhThuong.setBounds(10, 370, 120, 30);

        RdnKhoa.setText("Khóa");
        RdnKhoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RdnKhoaMouseClicked(evt);
            }
        });
        jPanel21.add(RdnKhoa);
        RdnKhoa.setBounds(150, 370, 120, 30);

        jPanel21.add(CbnNam);
        CbnNam.setBounds(210, 160, 90, 30);

        jPanel21.add(cbnNgay);
        cbnNgay.setBounds(10, 160, 50, 30);

        jPanel21.add(cbnThang);
        cbnThang.setBounds(110, 160, 57, 30);

        RdnNu.setText("Nữ");
        RdnNu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RdnNuMouseClicked(evt);
            }
        });
        jPanel21.add(RdnNu);
        RdnNu.setBounds(100, 210, 93, 23);

        RdnNam.setText("Nam");
        RdnNam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RdnNamMouseClicked(evt);
            }
        });
        jPanel21.add(RdnNam);
        RdnNam.setBounds(10, 210, 80, 23);

        jLabel2.setText(":");
        jPanel21.add(jLabel2);
        jLabel2.setBounds(80, 170, 10, 14);

        jLabel5.setText(":");
        jPanel21.add(jLabel5);
        jLabel5.setBounds(190, 170, 10, 14);

        jPanel13.add(jPanel21);

        jPanel2.add(jPanel13);
        jPanel13.setBounds(240, 20, 430, 430);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Trạng Thái");
        jPanel7.add(jLabel7);

        jPanel2.add(jPanel7);
        jPanel7.setBounds(10, 390, 230, 40);

        btndongy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_checkmark_20px_1.png"))); // NOI18N
        btndongy.setText("Đồng Ý");
        btndongy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndongyActionPerformed(evt);
            }
        });
        jPanel2.add(btndongy);
        btndongy.setBounds(90, 470, 140, 30);

        btnkhoiphucmatkhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_key_20px.png"))); // NOI18N
        btnkhoiphucmatkhau.setText("Khôi Phục Mật Khẩu");
        btnkhoiphucmatkhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkhoiphucmatkhauActionPerformed(evt);
            }
        });
        jPanel2.add(btnkhoiphucmatkhau);
        btnkhoiphucmatkhau.setBounds(270, 470, 240, 30);

        btnhuybo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_cross_mark_20px.png"))); // NOI18N
        btnhuybo.setText("Hủy Bỏ");
        btnhuybo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhuyboActionPerformed(evt);
            }
        });
        jPanel2.add(btnhuybo);
        btnhuybo.setBounds(540, 470, 120, 30);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Cập Nhật Người Dùng");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txttendangnhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttendangnhapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttendangnhapActionPerformed

    private void btnhuyboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhuyboActionPerformed

        this.dispose();

    }//GEN-LAST:event_btnhuyboActionPerformed

    private void RdnBinhThuongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RdnBinhThuongMouseClicked

        RdnKhoa.setSelected(false);

    }//GEN-LAST:event_RdnBinhThuongMouseClicked

    private void RdnKhoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RdnKhoaMouseClicked

        RdnBinhThuong.setSelected(false);
    }//GEN-LAST:event_RdnKhoaMouseClicked

    private void btndongyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndongyActionPerformed
        int option = JOptionPane.showConfirmDialog(null, "Bạn Có Muốn sửa Thông tin Này Không", "Nhắc Nhở", JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE, new ImageIcon(getClass().getResource("/img/icons8_ask_question_20px_3.png")));

        if (option == 0) {
            User Update = Const.session.get(User.class, Const.user_update.getUserName());
            Update.setUserName(txttendangnhap.getText());
            Update.setHovaTen(txthovaten.getText());
            Update.setEmail(txtemail.getText());
            if (RdnNam.isSelected()) {
                Update.setGioitinh("Nam");
            } else {
                Update.setGioitinh("Nữ");
            }
            String NgaySinh = CbnNam.getSelectedItem() + "-" + cbnThang.getSelectedItem() + "-" + cbnNgay.getSelectedItem();
            Update.setNgaySinh(Date.valueOf(NgaySinh));
            Update.setDiaChi(txtdiachi.getText());
            if (RdnBinhThuong.isSelected()) {
                Update.setTrangThai("Bình Thường");
            } else {
                Update.setTrangThai("Khóa");
            }

            Const.session.getTransaction().begin();
            Const.session.delete(Update);
            Const.session.save(Update);
            Const.session.getTransaction().commit();
            JOptionPane.showMessageDialog(null, "sửa Thành Công", "Nhắc Nhở", JOptionPane.INFORMATION_MESSAGE, new ImageIcon(getClass().getResource("/img/icons8_ask_question_20px_3.png")));
            Const.Load = false;
            this.dispose();

        } else {
            JOptionPane.showMessageDialog(null, "sửa Thất bại", "Nhắc Nhở", JOptionPane.INFORMATION_MESSAGE, new ImageIcon(getClass().getResource("/img/icons8_ask_question_20px_3.png")));

        }
    }//GEN-LAST:event_btndongyActionPerformed

    private void btnkhoiphucmatkhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkhoiphucmatkhauActionPerformed
        int option = JOptionPane.showConfirmDialog(null, "Bạn Có Muốn Reset Mật Khẩu Không", "Nhắc Nhở", JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE, new ImageIcon(getClass().getResource("/img/icons8_ask_question_20px_3.png")));
        if (option == 0) {
            String Search = Const.user_update.getUserName();
            User Update = Const.session.get(User.class, Search);
            Update.setPassword(txttendangnhap.getText());
            Const.session.getTransaction().begin();
            Const.session.save(Update);
            Const.session.getTransaction().commit();
            JOptionPane.showMessageDialog(null, "Thay Đổi Thành Công", "Nhắc Nhở", JOptionPane.INFORMATION_MESSAGE, new ImageIcon(getClass().getResource("/img/icons8_ask_question_20px_3.png")));

            Const.Load = false;

            this.dispose();
        } else if (option == 1) {
            JOptionPane.showMessageDialog(null, "Thay Đổi Thất bại", "Nhắc Nhở", JOptionPane.INFORMATION_MESSAGE, new ImageIcon(getClass().getResource("/img/icons8_ask_question_20px_3.png")));

        } else {

        }
    }//GEN-LAST:event_btnkhoiphucmatkhauActionPerformed
    private void AddDate() {
        for (int i = 1; i <= 9; i++) {
            cbnNgay.addItem(0 + "" + i);

        }
        for (int i = 10; i <= 31; i++) {
            cbnNgay.addItem("" + i);

        }
        for (int i = 1; i <= 9; i++) {
            cbnThang.addItem(0 + "" + i);

        }
        for (int i = 10; i <= 12; i++) {
            cbnThang.addItem("" + i);

        }
        for (int i = 1991; i <= 2200; i++) {
            CbnNam.addItem("" + i);

        }
    }
    private void RdnNamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RdnNamMouseClicked
        RdnNu.setSelected(false);
    }//GEN-LAST:event_RdnNamMouseClicked

    private void RdnNuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RdnNuMouseClicked
        RdnNam.setSelected(false);
    }//GEN-LAST:event_RdnNuMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CbnNam;
    private javax.swing.JRadioButton RdnBinhThuong;
    private javax.swing.JRadioButton RdnKhoa;
    private javax.swing.JRadioButton RdnNam;
    private javax.swing.JRadioButton RdnNu;
    private javax.swing.JButton btndongy;
    private javax.swing.JButton btnhuybo;
    private javax.swing.JButton btnkhoiphucmatkhau;
    private javax.swing.JComboBox<String> cbnNgay;
    private javax.swing.JComboBox<String> cbnThang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtdiachi;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txthovaten;
    private javax.swing.JTextField txttendangnhap;
    // End of variables declaration//GEN-END:variables

    public void LoadWindow() {

        setSize(749, 690);
        setVisible(true);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(HIDE_ON_CLOSE);

    }
}
