/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Component;

import Hiberneat.User.User;
import Login.Const;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseListener;
import java.sql.Date;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Vector;
import javax.persistence.Query;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author admin
 */
public class Form_AddUser extends javax.swing.JFrame {

    boolean oppen = true;
    Admin admin;

    public boolean isOppen() {
        return oppen;
    }

    public void setOppen(boolean oppen) {
        this.oppen = oppen;
    }

    public Form_AddUser() {

        initComponents();
        AddDate();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        txtHoveTen = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtTendangnhap = new javax.swing.JTextField();
        cbnNam = new javax.swing.JComboBox<>();
        jcomboquyen = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtdiachi = new javax.swing.JTextArea();
        RdnBinhThuong = new javax.swing.JRadioButton();
        RdnKhoa = new javax.swing.JRadioButton();
        txtmatkhau1 = new javax.swing.JTextField();
        cbnNgay = new javax.swing.JComboBox<>();
        cbnThang = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        RdnNam = new javax.swing.JRadioButton();
        RdnNu = new javax.swing.JRadioButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        btndongy = new javax.swing.JButton();
        btnhuybo = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setUndecorated(true);
        setResizable(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông Tin"));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.setLayout(null);

        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.Y_AXIS));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Họ Và Tên");
        jPanel6.add(jLabel4);

        jPanel5.add(jPanel6);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Email");
        jPanel9.add(jLabel13);

        jPanel5.add(jPanel9);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Tên Đăng Nhập");
        jPanel8.add(jLabel9);

        jPanel5.add(jPanel8);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Mật Khẩu");
        jPanel4.add(jLabel3);

        jPanel5.add(jPanel4);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Ngày Sinh");
        jPanel10.add(jLabel15);

        jPanel5.add(jPanel10);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Giới Tính");
        jPanel12.add(jLabel11);

        jPanel5.add(jPanel12);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Chức Vụ");
        jPanel15.add(jLabel14);

        jPanel5.add(jPanel15);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Địa Chỉ");
        jPanel11.add(jLabel12);

        jPanel5.add(jPanel11);

        jPanel2.add(jPanel5);
        jPanel5.setBounds(10, 30, 230, 320);

        jPanel13.setLayout(new javax.swing.BoxLayout(jPanel13, javax.swing.BoxLayout.Y_AXIS));

        jPanel21.setAlignmentX(15.0F);
        jPanel21.setLayout(null);

        txtHoveTen.setAlignmentY(0.0F);
        jPanel21.add(txtHoveTen);
        txtHoveTen.setBounds(10, 10, 410, 30);

        txtEmail.setAlignmentY(0.0F);
        jPanel21.add(txtEmail);
        txtEmail.setBounds(10, 50, 410, 30);

        txtTendangnhap.setAlignmentY(0.0F);
        jPanel21.add(txtTendangnhap);
        txtTendangnhap.setBounds(10, 90, 410, 30);

        cbnNam.setAlignmentX(0.0F);
        jPanel21.add(cbnNam);
        cbnNam.setBounds(250, 170, 90, 30);

        jcomboquyen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "GiaoVien", "SinhVien", "User" }));
        jcomboquyen.setAlignmentX(0.0F);
        jPanel21.add(jcomboquyen);
        jcomboquyen.setBounds(10, 250, 100, 30);

        txtdiachi.setColumns(20);
        txtdiachi.setRows(5);
        jScrollPane1.setViewportView(txtdiachi);

        jPanel21.add(jScrollPane1);
        jScrollPane1.setBounds(10, 290, 410, 100);

        RdnBinhThuong.setText("Bình Thường\n\n");
        RdnBinhThuong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RdnBinhThuongMouseClicked(evt);
            }
        });
        jPanel21.add(RdnBinhThuong);
        RdnBinhThuong.setBounds(10, 390, 120, 30);

        RdnKhoa.setText("Khóa");
        RdnKhoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RdnKhoaMouseClicked(evt);
            }
        });
        jPanel21.add(RdnKhoa);
        RdnKhoa.setBounds(150, 390, 120, 30);

        txtmatkhau1.setAlignmentY(0.0F);
        jPanel21.add(txtmatkhau1);
        txtmatkhau1.setBounds(10, 130, 410, 30);

        cbnNgay.setAlignmentX(0.0F);
        jPanel21.add(cbnNgay);
        cbnNgay.setBounds(10, 170, 50, 30);

        cbnThang.setAlignmentX(0.0F);
        jPanel21.add(cbnThang);
        cbnThang.setBounds(130, 170, 50, 30);

        jLabel2.setText(":");
        jPanel21.add(jLabel2);
        jLabel2.setBounds(90, 180, 20, 14);

        jLabel5.setText(":");
        jPanel21.add(jLabel5);
        jLabel5.setBounds(210, 180, 20, 14);

        RdnNam.setText("Nam");
        RdnNam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RdnNamMouseClicked(evt);
            }
        });
        jPanel21.add(RdnNam);
        RdnNam.setBounds(10, 210, 70, 23);

        RdnNu.setText("Nữ");
        jPanel21.add(RdnNu);
        RdnNu.setBounds(130, 210, 70, 23);

        jPanel13.add(jPanel21);

        jPanel2.add(jPanel13);
        jPanel13.setBounds(240, 20, 430, 430);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Trạng Thái");
        jPanel7.add(jLabel7);

        jPanel2.add(jPanel7);
        jPanel7.setBounds(10, 410, 230, 40);

        btndongy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_checkmark_20px_1.png"))); // NOI18N
        btndongy.setText("Đồng Ý");
        btndongy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndongyActionPerformed(evt);
            }
        });
        jPanel2.add(btndongy);
        btndongy.setBounds(250, 470, 140, 30);

        btnhuybo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_cross_mark_20px.png"))); // NOI18N
        btnhuybo.setText("Hủy Bỏ");
        btnhuybo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhuyboActionPerformed(evt);
            }
        });
        jPanel2.add(btnhuybo);
        btnhuybo.setBounds(540, 470, 120, 30);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Thêm Tài Khoản Người Dùng");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(111, 111, 111))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnhuyboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhuyboActionPerformed
        setOppen(!oppen);
        this.dispose();

    }//GEN-LAST:event_btnhuyboActionPerformed

    private void btndongyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndongyActionPerformed
        int option = JOptionPane.showConfirmDialog(null, "Bạn Có Muốn Thêm Thông tin Này Không", "Nhắc Nhở", JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE, new ImageIcon(getClass().getResource("/img/icons8_ask_question_20px_3.png")));
        if (option == 0) {
            if (CheckUserName()) {
                JOptionPane.showMessageDialog(null, "Tài khoản này Đã Tồn Tại Vui lòng Nhập Tài Khoản Khác", "Nhắc Nhở", JOptionPane.INFORMATION_MESSAGE, new ImageIcon(getClass().getResource("/img/icons8_ask_question_20px_3.png")));

            } else {
                User user = new User();
                user.setHovaTen(txtHoveTen.getText());
                user.setEmail(txtEmail.getText());
                user.setUserName(txtTendangnhap.getText());
                user.setPassword(txtmatkhau1.getText());
                String NgaySinh = cbnNam.getSelectedItem() + "-" + cbnThang.getSelectedItem() + "-" + cbnNgay.getSelectedItem();
                user.setNgaySinh(Date.valueOf(NgaySinh));
                System.out.println("" + NgaySinh);
                if (RdnNam.isSelected()) {
                    user.setGioitinh("Nam");
                } else {
                    user.setGioitinh("Nữ");
                }
                user.setQuyen((String) jcomboquyen.getSelectedItem());
                user.setDiaChi(txtdiachi.getText());
                if (RdnBinhThuong.isSelected()) {
                    user.setTrangThai("Bình Thường");
                } else {
                    user.setTrangThai("Khóa");
                }
                Const.session.getTransaction().begin();
                Const.session.save(user);
                Const.session.getTransaction().commit();
                JOptionPane.showMessageDialog(null, "Thêm Thành Công", "Nhắc Nhở", JOptionPane.INFORMATION_MESSAGE, new ImageIcon(getClass().getResource("/img/icons8_ask_question_20px_3.png")));
                admin = new Admin();
                admin.LoadDataResource();
                setOppen(!oppen);
                this.dispose();
            }

        } else if (option == 1) {
            JOptionPane.showMessageDialog(null, "Thêm Thất Bại", "Nhắc Nhở", JOptionPane.INFORMATION_MESSAGE, new ImageIcon(getClass().getResource("/img/icons8_ask_question_20px_3.png")));

        } else {

        }
    }//GEN-LAST:event_btndongyActionPerformed

    private void RdnBinhThuongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RdnBinhThuongMouseClicked

        RdnKhoa.setSelected(false);


    }//GEN-LAST:event_RdnBinhThuongMouseClicked

    private void RdnKhoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RdnKhoaMouseClicked

        RdnBinhThuong.setSelected(false);


    }//GEN-LAST:event_RdnKhoaMouseClicked

    private void RdnNamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RdnNamMouseClicked

        RdnNu.setSelected(false);

    }//GEN-LAST:event_RdnNamMouseClicked
    private boolean CheckUserName() {
        Const.ListUser = null;
        Query q = Const.session.createQuery("FROM User");
        Const.ListUser = q.getResultList();
        Vector<Object> CheckuserName = new Vector<>();;
        for (int i = 0; i < Const.ListUser.size(); i++) {

            CheckuserName.add(Const.ListUser.get(i).getUserName());
        }
        for (int i = 0; i < CheckuserName.size(); i++) {
            if (txtTendangnhap.getText().equals(CheckuserName.get(i))) {
                return true;
            }

        }
        return false;
    }

    private void AddDate() {
        for (int i = 1; i <= 9; i++) {
            cbnNgay.addItem(0 + "" + i);

        }
        for (int i = 10; i <= 31; i++) {
            cbnNgay.addItem("" + i);

        }
        for (int i = 1; i <= 9; i++) {
            cbnThang.addItem(0 + "" + i);

        }
        for (int i = 10; i <= 12; i++) {
            cbnThang.addItem("" + i);

        }
        for (int i = 1991; i <= 2200; i++) {
            cbnNam.addItem("" + i);

        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RdnBinhThuong;
    private javax.swing.JRadioButton RdnKhoa;
    private javax.swing.JRadioButton RdnNam;
    private javax.swing.JRadioButton RdnNu;
    private javax.swing.JButton btndongy;
    private javax.swing.JButton btnhuybo;
    private javax.swing.JComboBox<String> cbnNam;
    private javax.swing.JComboBox<String> cbnNgay;
    private javax.swing.JComboBox<String> cbnThang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcomboquyen;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtHoveTen;
    private javax.swing.JTextField txtTendangnhap;
    private javax.swing.JTextArea txtdiachi;
    private javax.swing.JTextField txtmatkhau1;
    // End of variables declaration//GEN-END:variables

    public void LoadWindow() {

        setSize(749, 690);
        setVisible(true);
        setLocationRelativeTo(null);

//        setDefaultCloseOperation(HIDE_ON_CLOSE);
    }

}
