/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Component;

import Hiberneat.User.User;
import Login.Const;
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author admin
 */
public class Thongtin extends javax.swing.JPanel {

    boolean Edit = true;

    public Thongtin() {
        initComponents();
        setOpaque(false);
        AddDate();
        LoadDataLen();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        BtnCapNhatThongTin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        TxtHovaTen = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TxtEmail = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        CbnNgay = new javax.swing.JComboBox<>();
        CbnThang = new javax.swing.JComboBox<>();
        CbnNam = new javax.swing.JComboBox<>();
        RdnNam = new javax.swing.JRadioButton();
        RdnNu = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxtDiaChi = new javax.swing.JTextArea();

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel2.setOpaque(false);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Male_User_100px_2.png"))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Thông Tin Cá Nhân");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setOpaque(false);

        BtnCapNhatThongTin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/suado_20.png"))); // NOI18N
        BtnCapNhatThongTin.setText("Cập Nhật Thông Tin");
        BtnCapNhatThongTin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnCapNhatThongTin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCapNhatThongTinActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Họ Và Tên :");

        TxtHovaTen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TxtHovaTen.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Email :");

        TxtEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TxtEmail.setEnabled(false);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Giới Tính :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Ngày Sinh :");

        CbnNgay.setEnabled(false);

        CbnThang.setEnabled(false);

        CbnNam.setEnabled(false);

        RdnNam.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        RdnNam.setText("Nam");
        RdnNam.setEnabled(false);
        RdnNam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RdnNamMouseClicked(evt);
            }
        });
        RdnNam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RdnNamActionPerformed(evt);
            }
        });

        RdnNu.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        RdnNu.setText("Nữ");
        RdnNu.setEnabled(false);
        RdnNu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RdnNuMouseClicked(evt);
            }
        });
        RdnNu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RdnNuActionPerformed(evt);
            }
        });

        jLabel5.setText(":");

        jLabel6.setText(":");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Địa Chỉ :");

        TxtDiaChi.setColumns(20);
        TxtDiaChi.setRows(5);
        TxtDiaChi.setEnabled(false);
        jScrollPane1.setViewportView(TxtDiaChi);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnCapNhatThongTin))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtEmail)
                            .addComponent(TxtHovaTen)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RdnNam)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(CbnNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel5)))
                                .addGap(1, 1, 1)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RdnNu)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addComponent(CbnThang, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28)
                                        .addComponent(jLabel6)
                                        .addGap(30, 30, 30)
                                        .addComponent(CbnNam, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jScrollPane1))))
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtHovaTen, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(RdnNam)
                    .addComponent(RdnNu))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(CbnNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CbnThang, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CbnNam, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addComponent(BtnCapNhatThongTin, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(91, 91, 91))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(279, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(280, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(335, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(284, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void RdnNamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RdnNamActionPerformed
        RdnNu.setSelected(false);
    }//GEN-LAST:event_RdnNamActionPerformed

    private void RdnNuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RdnNuActionPerformed
        RdnNam.setSelected(false);
    }//GEN-LAST:event_RdnNuActionPerformed

    private void BtnCapNhatThongTinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCapNhatThongTinActionPerformed
        if (Edit) {
            BtnCapNhatThongTin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_checkmark_20px_1.png")));
            TxtEmail.setEnabled(true);
            TxtDiaChi.setEnabled(true);
            TxtHovaTen.setEnabled(true);
            RdnNam.setEnabled(true);
            RdnNu.setEnabled(true);
            CbnNam.setEnabled(true);
            CbnNgay.setEnabled(true);
            CbnThang.setEnabled(true);
            Edit = false;
            BtnCapNhatThongTin.setText("Lưu Thông Tin");
        } else {
            int option = JOptionPane.showConfirmDialog(null, "Bạn Có Muốn Cập Nhật Lại Thông Tin Này Không", "Nhắc Nhở", JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE, new ImageIcon(getClass().getResource("/img/icons8_warning_shield_20px_1.png")));

            if (option == 0) {
                BtnCapNhatThongTin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/suado_20.png")));
                TxtEmail.setEnabled(false);
                TxtDiaChi.setEnabled(false);
                TxtHovaTen.setEnabled(false);
                RdnNam.setEnabled(false);
                RdnNu.setEnabled(false);
                CbnNam.setEnabled(false);
                CbnNgay.setEnabled(false);
                CbnThang.setEnabled(false);
                BtnCapNhatThongTin.setText("Cập Nhật Thông Tin");
                User Sua = Const.session.get(User.class, Const.user.getUserName());
                Sua.setHovaTen(TxtHovaTen.getText());
                Sua.setEmail(TxtEmail.getText());
                String NgaySinh = CbnNam.getSelectedItem() + "-" + CbnThang.getSelectedItem() + "-" + CbnNgay.getSelectedItem();
                Sua.setNgaySinh(java.sql.Date.valueOf(NgaySinh));
                if (RdnNam.isSelected()) {
                    Sua.setGioitinh("Nam");
                } else {
                    Sua.setGioitinh("Nữ");
                }

                Sua.setDiaChi(TxtDiaChi.getText());
                Const.session.getTransaction().begin();
                Const.session.save(Sua);
                Const.session.getTransaction().commit();
                JOptionPane.showMessageDialog(null, "Cập Nhật Thành Công", "Nhắc Nhở", JOptionPane.INFORMATION_MESSAGE, new ImageIcon(getClass().getResource("/img/icons8_ask_question_20px_3.png")));
                Edit = true;
            } else {
                LoadDataLen();
                BtnCapNhatThongTin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/suado_20.png")));
                TxtEmail.setEnabled(false);
                TxtDiaChi.setEnabled(false);
                TxtHovaTen.setEnabled(false);
                RdnNam.setEnabled(false);
                RdnNu.setEnabled(false);
                CbnNam.setEnabled(false);
                CbnNgay.setEnabled(false);
                CbnThang.setEnabled(false);
                BtnCapNhatThongTin.setText("Cập Nhật Thông Tin");
                Edit = true;
                JOptionPane.showMessageDialog(null, "Cập Nhật Thất Bại", "Nhắc Nhở", JOptionPane.INFORMATION_MESSAGE, new ImageIcon(getClass().getResource("/img/icons8_ask_question_20px_3.png")));
            }

        }
    }//GEN-LAST:event_BtnCapNhatThongTinActionPerformed

    private void RdnNamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RdnNamMouseClicked
        RdnNu.setSelected(false);
    }//GEN-LAST:event_RdnNamMouseClicked

    private void RdnNuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RdnNuMouseClicked
        RdnNam.setSelected(false);
    }//GEN-LAST:event_RdnNuMouseClicked

    @Override
    protected void paintComponent(Graphics grphcs) {
        Graphics2D g2 = (Graphics2D) grphcs;
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        GradientPaint gra = new GradientPaint(0, 0, Color.white, getWidth(), 0, new Color(93, 58, 196));
        g2.setPaint(gra);
        g2.fillRect(0, 0, getWidth(), getHeight());
        super.paintComponent(grphcs);
    }

    public void LoadDataLen() {
        TxtHovaTen.setText(Const.user.getHovaTen());
        TxtEmail.setText(Const.user.getEmail());
        TxtDiaChi.setText(Const.user.getDiaChi());
        if (Const.user.getGioitinh().endsWith("Nam")) {
            RdnNam.setSelected(true);
        } else {
            RdnNu.setSelected(true);
        }
        String NgaySinh = Const.user.getNgaySinh().toString();
        String[] Tachchuoi = NgaySinh.split("-");

        CbnNam.setSelectedItem(Tachchuoi[0]);
        CbnThang.setSelectedItem(Tachchuoi[1]);
        CbnNgay.setSelectedItem(Tachchuoi[2]);

    }

    private void AddDate() {
        for (int i = 1; i <= 9; i++) {
            CbnNgay.addItem(0 + "" + i);

        }
        for (int i = 10; i <= 31; i++) {
            CbnNgay.addItem("" + i);

        }
        for (int i = 1; i <= 9; i++) {
            CbnThang.addItem(0 + "" + i);

        }
        for (int i = 10; i <= 12; i++) {
            CbnThang.addItem("" + i);

        }
        for (int i = 1991; i <= 2200; i++) {
            CbnNam.addItem("" + i);

        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCapNhatThongTin;
    private javax.swing.JComboBox<String> CbnNam;
    private javax.swing.JComboBox<String> CbnNgay;
    private javax.swing.JComboBox<String> CbnThang;
    private javax.swing.JRadioButton RdnNam;
    private javax.swing.JRadioButton RdnNu;
    private javax.swing.JTextArea TxtDiaChi;
    private javax.swing.JTextField TxtEmail;
    private javax.swing.JTextField TxtHovaTen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
